lab12-2/app/post/models.py
from datetime import datetime
from enum import Enum
from .. import db

class PostType(Enum):
    NEWS = 'news'
    PUBLICATION = 'publication'
    OTHER = 'other'

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    text = db.Column(db.String(1000))
    image = db.Column(db.String(255), default='postdefault.jpg')
    created = db.Column(db.TIMESTAMP, default=datetime.utcnow)
    types = db.Column(db.Enum(PostType), default=PostType.OTHER)
    enabled = db.Column(db.Boolean, default=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Post('{self.title}', '{self.created}')"

lab12-2/app/post/forms.py
from wtforms import BooleanField, FileField, StringField, TextAreaField, SelectField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm
from .models import PostType

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    types = SelectField('Types', choices=[(choice.name, choice.value) for choice in PostType], validators=[DataRequired()])
    enabled = BooleanField('Enabled')
    image = FileField('Image')
    submit = SubmitField('Submit')

lab12-2/app/post/__init__.py
from flask import Blueprint
from .models import Post

post_bp = Blueprint('post_bp', __name__, template_folder='templates/post')

from . import views

lab12-2/app/post/views.py
import os
import secrets
from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from . import post_bp
from .. import db, navigation
from .forms import PostForm
from .models import Post


@post_bp.context_processor
def inject_navigation():
    return dict(navigation=navigation())

@post_bp.route('/post/create', methods=['GET', 'POST'])
# @login_required
def create_post():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post(
            title=form.title.data,
            text=form.text.data,
            types=form.types.data,
            enabled=form.enabled.data,
            user_id=current_user.id
        )
        
        if form.image.data:
            picture_file = save_picture(form.image.data)
            new_post.image = picture_file

        db.session.add(new_post)
        db.session.commit()
        flash('Post added', 'success')
        return redirect(url_for('post_bp.posts'))

    return render_template('create_post.html', form=form)

@post_bp.route('/post', methods=['GET'])
def posts():
    posts = Post.query.all()
    return render_template('posts.html', posts=posts)

@post_bp.route('/post/<int:id>', methods=['GET'])
def view_post(id):
    post = Post.query.get_or_404(id)
    return render_template('view_post.html', post=post)

@post_bp.route('/post/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update_post(id):
    post = Post.query.get_or_404(id)
    form = PostForm(obj=post)

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        post.types = form.types.data
        post.enabled = form.enabled.data
        
        if form.image.data:
            picture_file = save_picture(form.image.data)
            post.image = picture_file

        db.session.commit()
        flash('Post updated', 'success')
        return redirect(url_for('post_bp.view_post', id=post.id))

    return render_template('update_post.html', form=form, post=post)

def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(post_bp.root_path, '../static/images/posts', picture_fn)
    form_picture.save(picture_path)
    return picture_fn

@post_bp.route('/post/<int:id>/delete', methods=['POST'])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted', 'success')
    return redirect(url_for('post_bp.posts'))

lab12-2/app/post/templates/post/create_post.html
{% extends 'base.html' %}

{% block title %}Додати пост{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col"></div>
        <div class="col-4">
            <h1 class="namesH">Додати пост</h1><hr>
            <form method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                {{ form.title.label (class="form-label") }} 
                {{ form.title(class="form-control") }} <br>
                {{ form.text.label (class="form-label") }} 
                {{ form.text(class="form-control") }} <br>
                {{ form.image.label (class="form-label") }} 
                {{ form.image(type="file", class="form-control") }} <br>
                {{ form.types.label (class="form-label") }} 
                {{ form.types(class="form-control") }} <br>
                {{ form.enabled.label (class="form-label") }} 
                {{ form.enabled(class="form-check-label") }} <br><hr>
                {{ form.submit(class="btn btn-primary") }}
            </form>
        </div>
        <div class="col"></div>
    </div>
    
</div>
{% include 'footer.html' %}
{% endblock %}

lab12-2/app/post/templates/post/posts.html
{% extends 'base.html' %}

{% block title %}Список постів{% endblock %}

{% block content %}
<div class="container" style="align-items: center; flex-direction: wrap;">
    <div class="posts-view" style="justify-content: center; flex-direction: column; align-items: center; display: flex;">
        <a href="{{ url_for('post_bp.create_post') }}" style="width: 200px; margin: 15px;" class="a_but btn btn-primary add-posts">Додати пост</a>
        <div class="row" style="display: flex; justify-content: center; flex-wrap: wrap;">
            {% for post in posts %}
                <div class="col-md-3 mb-3" style="background-color: var(--bg_color-2); padding: 25px; margin: 15px;">
                    <div class="card" style="display: flex; flex-direction: column; justify-content: center;">
                        <img src="{{ url_for('static', filename='images/posts/' + post.image) }}" alt="Post Image" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.types.value }} - {{ "Enabled" if post.enabled else "Disabled" }}</p>
                            <a class="a_but" href="{{ url_for('post_bp.view_post', id=post.id) }}" class="btn btn-primary">Переглянути</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include 'footer.html' %}
{% endblock %}

lab12-2/app/post/templates/post/update_post.html
{% extends 'base.html' %}

{% block title %}Оновлення поста{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col"></div>
        <div class="col-4">
            <h1 class="namesH">Оновлення поста</h1> <hr>
        <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ form.title.label(class="form-label") }} 
            {{ form.title(class="form-control") }} <br>
            {{ form.text.label(class="form-label") }} 
            {{ form.text(class="form-control") }} <br>
            {{ form.image.label(class="form-label") }} 
            {{ form.image(type="file", class="form-control") }} <br>
            {{ form.types.label(class="form-label") }} 
            {{ form.types(class="form-control") }} <br>
            {{ form.enabled.label(class="form-label") }} 
            {{ form.enabled(class="form-check-label") }} <br><hr>
            {{ form.submit(class="btn btn-primary") }}
        </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

lab12-2/app/post/templates/post/view_post.html
{% extends 'base.html' %}

{% block title %}Перегляд поста{% endblock %}

{% block content %}
<div class="container" style="justify-content: center; align-items: center; ">
    <div class="row">
        <div class="col"></div>
        <div class="" style="justify-content: center; display: flex; align-items: center; flex-direction: column; background-color: var(--bg_color-2); padding: 25px;">
            <h1>{{ post.title }}</h1>
            <img src="{{ url_for('static', filename='images/posts/' + post.image) }}" alt="Post Image" class="post-image">
            <p>Type: {{ post.types.value }}</p>
            <p>Text: {{ post.text }}</p>
            <p>Created: {{ post.created }}</p>
            
            {% if current_user.is_authenticated and current_user.id == post.user_id %}
               
                <form method="POST" action="{{ url_for('post_bp.delete_post', id=post.id) }}">
                    <a class="a_but" href="{{ url_for('post_bp.update_post', id=post.id) }} " class="btn btn-primary">Edit</a>
                    <button class="a_but" type="submit" class="btn btn-primary">Delete</button>
                </form>
            {% endif %}
        </div>
        <div class="col"></div>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}