lab12-2/app/todo/models.py
from .. import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    todo_item = db.Column(db.String(128), nullable=False)
    status = db.Column(db.Boolean, default=False)
    description = db.Column(db.String(256))

lab12-2/app/todo/forms.py
from wtforms import BooleanField, StringField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm

class TodoForm(FlaskForm):
    todo_item = StringField('Todo Item', validators=[DataRequired()])
    status = BooleanField('Status')
    description = StringField('Description')
    submit = SubmitField('Submit')

lab12-2/app/todo/__init__.py
from flask import Blueprint

todo = Blueprint('todo', __name__, template_folder='templates/todo')

from . import views

lab12-2/app/todo/views.py
from flask import flash, redirect, render_template, url_for
from . import todo
from .forms import TodoForm
from .models import Todo
from .. import db, navigation

@todo.context_processor
def inject_navigation():
    return dict(navigation=navigation())

@todo.route('/todo', methods=['GET', 'POST'])
def todos():
    todos = Todo.query.all()
    form = TodoForm()

    if form.validate_on_submit():
        new_todo = Todo(todo_item=form.todo_item.data, status=form.status.data, description=form.description.data)
        db.session.add(new_todo)
        db.session.commit()
        flash('Todo додано', 'success')
        return redirect(url_for('todo.todos'))

    return render_template('todo.html', todos=todos, form=form)


@todo.route('/todo/edit/<int:id>', methods=['GET', 'POST'])
def edit_todo(id):
    todo = Todo.query.get_or_404(id)
    form = TodoForm(obj=todo)

    if form.validate_on_submit():
        todo.todo_item = form.todo_item.data
        todo.status = form.status.data
        todo.description = form.description.data
        db.session.commit()
        flash('Todo оновлено', 'success')
        return redirect(url_for('todo.todos'))

    return render_template('edit_todo.html', form=form, todo=todo)


@todo.route('/todo/delete/<int:id>', methods=['POST'])
def delete_todo(id):
    todo = Todo.query.get_or_404(id)
    db.session.delete(todo)
    db.session.commit()
    flash('Todo видалено', 'success')
    return redirect(url_for('todo.todos'))

lab12-2/app/todo/templates/todo/edit_todo.html
{% extends 'base.html' %}

{% block title %}Редагування Todo{% endblock %}

{% block content %}
    <div class="todo_add">
        <h1>Редагування Todo</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.todo_item.label }} {{ form.todo_item(class="inputs") }} <br>
            {{ form.description.label }} {{ form.description(class="inputs") }} <br>
            {{ form.status.label }} {{ form.status }} <br><br>
            {{ form.submit(class="btn_submit") }}
        </form>
    </div>
{% endblock %}

lab12-2/app/todo/templates/todo/todo.html
{% extends 'base.html' %}

{% block title %}Список Todo{% endblock %}

{% block content %}
<div class="container">
    <div class="todo_add">
        <h1 class="namesH">Додати нове Todo</h1>
        <hr>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.todo_item.label }} {{ form.todo_item(class="inputs") }} <br>
            {{ form.description.label }} {{ form.description(class="inputs") }} <br>
            {{ form.status.label }} {{ form.status}} <br>
            {{ form.submit(class="btn_submit") }}
        </form>

        <hr>
        <h1 class="namesH">Список Todo</h1>
        <hr>
        <table class="todo_table">
            <table>
                <tr class="todo_list_title">
                    <th>No.</th>
                    <th>Todo_Item</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                {% for todo in todos %}
                <tr class="todo_list_obj">
                    <td>{{ todo.id }}</td>
                    <td>{{ todo.todo_item }}</td>
                    <td>{{ 'Done' if todo.status else 'Not Done' }}</td>
                    <td>
                       
                        <form method="post" action="{{ url_for('todo.delete_todo', id=todo.id) }}">
                            <a href="{{ url_for('todo.edit_todo', id=todo.id) }}">Edit</a>
                            <button type="submit" class="btn-link">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </table>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}